version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - printenv
      - echo "installing something"
  pre_build:
    commands:
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo "we are in the build phase"
      - echo "we will run some test"
      - grep -Fq "demo-code-build" pom.xml
  post_build:
    commands:
      - echo "we are in the post_build phase"
    
  artifacts:
    files:
      - '**.*'
      - name: demo-codebuild      
      